# Numerical Derivative
- [[LaTex] Markdown 수식 작성법](https://velog.io/@d2h10s/LaTex-Markdown-%EC%88%98%EC%8B%9D-%EC%9E%91%EC%84%B1%EB%B2%95)

## 상미분 
- $
\displaystyle f^{'}(x) = \frac{df(x)}{dx}
=\displaystyle\lim_{\Delta{x}\to 0} \frac{f(x+\Delta{x})-f(x)}{\Delta{x}}
=\displaystyle\lim_{\Delta{x}\to 0} \frac{f(x+\Delta{x})-f(x-\Delta{x})}{2\Delta{x}}
$


- <b>[예제1]</b> 함수 $f(x)=x^2$ 에서 미분계수 $f^{'}(3)$ 을 구하기.  
즉, $x=3$ 에서 값이 미세하게 변할 때, 함수 $f$는 얼마나 변하는지 계산하라는 의미


- $
\displaystyle f^{'}(3)  
=\displaystyle\lim_{\Delta{x}\to 0} \frac{f(3+e^{-4})-f(3-e^{-4})}{2*e^{-4}} = 6.0
$

- <b>[예제2]</b> 함수 $f(x)=3xe^x$ 에서 미분계수 $f^{'}(2)$ 을 구하기.  
즉, $x=2$ 에서 값이 미세하게 변할 때, 함수 $f$는 얼마나 변하는지 계산하라는 의미


- $\displaystyle f(x)=3xe^x $
- $\displaystyle f^{'}(x)= 3e^{x} + 3xe^x  $
- $\displaystyle f^{'}(2)= 3e^{2} + 3\cdot2e^2  $

In [1]:
def my_func1(x):
    return x**2

def numerical_derivative(f,x):
    delta_x = 1e-4
    return (f(x+delta_x) - f(x-delta_x))/(2*delta_x)

result = numerical_derivative(my_func1,3)
print("f(3) = x**2 =", my_func1(3))
print("f\'(3)= 2x = ", result)

f(3) = x**2 = 9
f'(3)= 2x =  6.000000000012662


In [2]:
import numpy as np

def my_func2(x):
    return (3*x*(np.exp(x)))

def numerical_derivative(f,x):
    delta_x = 1e-4
    return (f(x+delta_x) - f(x-delta_x))/(2*delta_x)

result = numerical_derivative(my_func2,2)
f_dev2 = 3*np.exp(2)+3*2*np.exp(2)
print("f\'(2) analytical = ", f_dev2)
print("f\'(2) numerical  = ", result)


f'(2) analytical =  66.50150489037586
f'(2) numerical  =  66.50150507518049


## 편미분

- 입력 변수가 하나 이상인 다변수 함수의 경우, 입력변수는 서로 돌깁적이기 때문에 편미분 수행.


- [예] $f(x,y)=2x+3xy+y^2$, 입력변수 $x,y$ 두개 이므로 $\displaystyle\frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}$ 각각 수행


- $\displaystyle f^{'}(1.0, 2.0) = (8.0, 15.0)$
- $x=1.0$ 에서의 미분계수는 변수 $y=2.0$을 상수로 대입하여 $\displaystyle\frac{\partial f(x,2)}{\partial x}$를 수행. 


- $y=2.0$ 에서의 미분계수는 변수 $x=1.0$을 상수로 대입하여 $\displaystyle\frac{\partial f(1,y)}{\partial y}$를 수행. 

In [4]:
import numpy as np

def my_func1(input_obj):
    x = input_obj[0]
    return (x**2)

def my_func2(input_obj):
    x = input_obj[0]
    y = input_obj[1]
    return (2*x+3*x*y+y**3)

def numerical_derivative(f,x):  # x: 모든 변수를 포함하는 numpy 객체 (행렬)
    delta_x = 1e-4
    # 계산된 수치미분값 저장 장소, 입력변수와 같은크기의 행렬로 생성.
    grad = np.zeros_like(x)  
    
    print("debug 1. initial input variable =", x)
    print("debug 2. initial grad =", grad)
    print("========================================")
    # 모든 입력변수에 대해 편미분을 하기위해 iterator 획득 
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx=it.multi_index
        # numpy 데이터는 mutable하므로 원본 데이터 백업.
        print("debug 3. idx = ",idx, ", x[idx] = ", x[idx])  # 입력변수 index 
        print(x)    # 입력변수 모니터링
        tmp_val=x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)  # f(x+delta_x)
        print(x)    # 입력변수 모니터링
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)  # f(x-delta_x)
        grad[idx] = (fx1 - fx2)/(2*delta_x)
        print(x)    # 입력변수 모니터링

        print("debug 4. grad[idx] =", grad[idx])
        print("debug 5. grad =", grad)
        print("========================================")

        x[idx] = tmp_val
        it.iternext()
        
    return grad

print("-------- func1 --------")
result = numerical_derivative(my_func1,np.array([3.0]))
print("result = ", result)

print("\n-------- func2 --------")
input = np.array([1.0,2.0])
result = numerical_derivative(my_func2,input)
print("result = ", result)

-------- func1 --------
debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
[3.]
[3.0001]
[2.9999]
debug 4. grad[idx] = 6.000000000012662
debug 5. grad = [6.]
result =  [6.]

-------- func2 --------
debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
[1. 2.]
[1.0001 2.    ]
[0.9999 2.    ]
debug 4. grad[idx] = 7.999999999990237
debug 5. grad = [8. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
[1. 2.]
[1.     2.0001]
[1.     1.9999]
debug 4. grad[idx] = 15.000000010019221
debug 5. grad = [ 8.         15.00000001]
result =  [ 8.         15.00000001]


## 4변수 편미분

- 입력변수 4개인 함수
- $f(w,x,y,z)=wx+xyz+3w+zy^2 \rightarrow f^{'}(1.0, 2.0, 3.0, 4.0)$


- input_obj 는 행렬 형태로 사용 
- $
input$_$obj=
\begin{bmatrix}
w & x \\
y & z 
\end{bmatrix} $
$=
\begin{bmatrix}
1 & 2 \\
3 & 4 
\end{bmatrix}
$


- $w = input$_$obj \ [0,0]$
- $x \ = input$_$obj \ [0,1]$
- $y \ = input$_$obj \ [1,0]$
- $z \ = input$_$obj \ [1,1]$

In [4]:
def my_func3(input_obj):
    w = input_obj[0,0]
    x = input_obj[0,1]
    y = input_obj[1,0]
    z = input_obj[1,1]
    return (w*x + x*y*z + 3*w + z*y**2)

input = np.array([[1.0,2.0],[3.0,4.0]])
result = numerical_derivative(my_func3,input)
print("result = ", result)

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
[[1. 2.]
 [3. 4.]]
[[1.0001 2.    ]
 [3.     4.    ]]
[[0.9999 2.    ]
 [3.     4.    ]]
debug 4. grad[idx] = 5.000000000023874
debug 5. grad = [[5. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
[[1. 2.]
 [3. 4.]]
[[1.     2.0001]
 [3.     4.    ]]
[[1.     1.9999]
 [3.     4.    ]]
debug 4. grad[idx] = 13.00000000000523
debug 5. grad = [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
[[1. 2.]
 [3. 4.]]
[[1.     2.    ]
 [3.0001 4.    ]]
[[1.     2.    ]
 [2.9999 4.    ]]
debug 4. grad[idx] = 32.00000000006753
debug 5. grad = [[ 5. 13.]
 [32.  0.]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
[[1. 2.]
 [3. 4.]]
[[1.     2.    ]
 [3.     4.0001]]
[[1.     2.    ]
 [3.     3.9999]]
debug 4. grad[idx] = 15.000000000000568
debug 5. grad = [[ 5. 13.]
 [32. 15.]]
result =  [[ 5. 13.]
 [32. 15.]]
